### ISSUE TITLE
I'm not getting any MQTT responses

### ISSUE THREAD

**Issue by stevearmitage** [tonyldo/ttlockio#9]
The configuration seems to work

``` 
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun ttlock2mqtt (no readiness notification)
s6-rc: info: service legacy-services successfully started
[09:04:30] INFO: Run application...
2022-08-24 09:04:31 - [DEBUG] TTLOCK2MQTT: Options: [CLIENT ID], [ACCESS TOKEN], core-mosquitto, 1883, addons, mi6eemeingu3Cai8chi5einaeng3aitiuKiivei5osheiXuchohShie0Quohri5j, DEBUG, 60, 300, 200
2022-08-24 09:04:31 - [DEBUG] TTLOCK2MQTT: Starting main loop...
2022-08-24 09:04:31 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): api.ttlock.com:443
2022-08-24 09:04:32 - [DEBUG] TTLOCK2MQTT: https://api.ttlock.com:443 "GET /v3/gateway/list?clientId=[CLIENT ID]&accessToken=[ACCESS TOKEN]&pageNo=1&pageSize=20&date=1661303071291 HTTP/1.1" 200 56
2022-08-24 09:04:32 - [INFO] TTLOCK2MQTT: Current threads: 1
2022-08-24 09:04:32 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): api.ttlock.com:443
2022-08-24 09:04:33 - [DEBUG] TTLOCK2MQTT: https://api.ttlock.com:443 "GET /v3/gateway/list?clientId=[CLIENT ID]&accessToken=[ACCESS TOKEN]&pageNo=1&pageSize=20&date=1661303072451 HTTP/1.1" 200 56
2022-08-24 09:04:33 - [INFO] TTLOCK2MQTT: Current threads: 1
2022-08-24 09:04:33 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): api.ttlock.com:443
```

But I get no MQTT messages - what's wrong?

**Comment by AlvaroBrasilia** [comment]
---------- Forwarded message ---------
De: lock smart ***@***.***>
Date: qua., 24 de ago. de 2022 às 05:36
Subject: Action required: Please update the domain of TTLock APIs you are
requesting
To: ***@***.***>


Dear Developer,

In response to the legal requirements for better data security and privacy
protection, we have assigned different domain names to users from China and
other countries. Please be reminded to update the domain name if you are
using any of our API. For software used in China, please call the China
domain name. Otherwise, please call the domain name for users out of China.
Following are the details：

Original domain name: api.ttlock.com
New domain name (China): cnapi.ttlock.com
New domain name (Out of China): euapi.ttlock.com

Original domain name: api.sciener.com
New domain name (China): cnapi.sciener.com
New domain name (Out of China): euapi.sciener.com

The original domain name will be deleted and no longer in service after
Oct. 1st, 2022. Your speedy action is highly appreciated.

If you need any assistance, please feel free to contact us at ***@***.***


Best Regards,
Sciener/TTLock Team


尊敬的开发者：


为了响应各国法律监管要求，完善数据保护，我们将对开放平台的接口域名进行调整，区分国内与国外的域名。在国内使用的软件请调用国内的域名，在国外使用的软件请调用国外的域名。具体变动如下：

原接口域名：api.ttlock.com
新接口域名（国内）：cnapi.ttlock.com
新接口域名（国外）：euapi.ttlock.com

原接口域名：api.sciener.com
新接口域名（国内）：cnapi.sciener.com
新接口域名（国外）：euapi.sciener.com

      原来的域名将在2022年10月1日后停止使用，请尽快完成更新，以免影响使用。如有疑问，欢迎联系我们。感谢您的信任与支持！

      顺祝商祺！

科技侠
通通锁
杭州赛脑智能控制技术有限公司

**Comment by stevearmitage** [comment]
I'm not sure how i can use that?

**Comment by tonyldo** [comment]
It s  look like u don t have any gateway or locks at your application user. U need to do this:

From Readme:
5 - Test your USER:
Download TTLock App at your cellphones app store. Log in with your YOUR_APP_NAME_CONCAT_NEW_NAME_FOR_YOUR_USER and NEW_PASS_FOR_YOUR_USER created on step four.
Add your TTLock gateways and locks.


> The configuration seems to work
> 
> ```
> s6-rc: info: service s6rc-oneshot-runner: starting
> s6-rc: info: service s6rc-oneshot-runner successfully started
> s6-rc: info: service fix-attrs: starting
> s6-rc: info: service fix-attrs successfully started
> s6-rc: info: service legacy-cont-init: starting
> s6-rc: info: service legacy-cont-init successfully started
> s6-rc: info: service legacy-services: starting
> services-up: info: copying legacy longrun ttlock2mqtt (no readiness notification)
> s6-rc: info: service legacy-services successfully started
> [09:04:30] INFO: Run application...
> 2022-08-24 09:04:31 - [DEBUG] TTLOCK2MQTT: Options: [CLIENT ID], [ACCESS TOKEN], core-mosquitto, 1883, addons, mi6eemeingu3Cai8chi5einaeng3aitiuKiivei5osheiXuchohShie0Quohri5j, DEBUG, 60, 300, 200
> 2022-08-24 09:04:31 - [DEBUG] TTLOCK2MQTT: Starting main loop...
> 2022-08-24 09:04:31 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): api.ttlock.com:443
> 2022-08-24 09:04:32 - [DEBUG] TTLOCK2MQTT: https://api.ttlock.com:443 "GET /v3/gateway/list?clientId=[CLIENT ID]&accessToken=[ACCESS TOKEN]&pageNo=1&pageSize=20&date=1661303071291 HTTP/1.1" 200 56
> 2022-08-24 09:04:32 - [INFO] TTLOCK2MQTT: Current threads: 1
> 2022-08-24 09:04:32 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): api.ttlock.com:443
> 2022-08-24 09:04:33 - [DEBUG] TTLOCK2MQTT: https://api.ttlock.com:443 "GET /v3/gateway/list?clientId=[CLIENT ID]&accessToken=[ACCESS TOKEN]&pageNo=1&pageSize=20&date=1661303072451 HTTP/1.1" 200 56
> 2022-08-24 09:04:33 - [INFO] TTLOCK2MQTT: Current threads: 1
> 2022-08-24 09:04:33 - [DEBUG] TTLOCK2MQTT: Starting new HTTPS connection (1): api.ttlock.com:443
> ```
> 
> But I get no MQTT messages - what's wrong?

**Comment by stevearmitage** [comment]
Ok, i reset the lock, used the admin login and it's working perfectly. I get if the gateway is connected, the battery level and the lock status. A cycle time of 60 seconds is too long for the lock reporting - is there a minimum I should use - every 10 seconds or less? Our door automatically relocks after 30 seconds, so with a 60 second window, it's unlikely to record an unlock event.

**Comment by tonyldo** [comment]
the time for scan locks states may be analyze with careful and tests.
